### ISSUE TITLE
Cannot mark members as protected in classDiagram

### ISSUE THREAD

**Issue by ChristopherStryker** [mermaid-js/mermaid#1061]
Attempting to mark a member as protected in a class diagram by using the octothorpe (hash) character causes the graph to not render. I'm attempting this based on the [classDiagram documentation](https://mermaidjs.github.io/#/classDiagram?id=visibility).

Specifically, the following code:

    classDiagram
    class MyClass
    MyClass : #mytest

Causes the following error:

    Parse error on line 3:
    ...s MyClassMyClass : #mytest
    ----------------------^
    Expecting 'NEWLINE', 'EOF', got 'PUNCTUATION'

The private, public and package qualifiers all seem to work appropriately.

This reproduces using the [Mermaid Live Editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jbGFzcyBNeUNsYXNzXG5NeUNsYXNzIDogI215dGVzdFxuXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ/error/UGFyc2UgZXJyb3Igb24gbGluZSAzOgouLi5zIE15Q2xhc3NNeUNsYXNzIDogI215dGVzdAotLS0tLS0tLS0tLS0tLS0tLS0tLS0tXgpFeHBlY3RpbmcgJ05FV0xJTkUnLCAnRU9GJywgZ290ICdQVU5DVFVBVElPTic)

I'm using Windows 10 with Chrome 78.0.3904.87

I can work around this cosmetically by using [`#35;`](https://github.com/mermaid-js/mermaid/issues/947) but it took me a while to figure that out. It's unclear to me whether I lose any functionality by doing so. (I believe not.)

**Comment by Dunning-Kruger** [comment]
The documentation shows to use `#` for protected. I assume this SHOULD work as the opening post suggests. Kept as bug.

**Comment by jgreywolf** [comment]
Interestingly, if you define the class with members inside of {}, this error does not happen. So it only appears to be when you are adding members individually

```
class BankAccount{
  +String onwer
  +BigDecimal balance
  #deposit(amount)
  +withdrawl(amount)
}
```

[(Live Editor)](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jbGFzcyBCYW5rQWNjb3VudHtcbiAgK1N0cmluZyBvbndlclxuICArQmlnRGVjaW1hbCBiYWxhbmNlXG4gICNkZXBvc2l0KGFtb3VudClcbiAgK3dpdGhkcmF3bChhbW91bnQpXG59XG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)

**Comment by ChristopherStryker** [comment]
jgreywolf, that's good to know. Unfortunately, I can't use the {} syntax at this time due to a GitLab bug: https://gitlab.com/gitlab-org/gitlab/issues/35584

**Comment by chris579** [comment]
Regarding your filled issue, the errors you described there are associated to older versions of mermaid. GitLab needs to update their mermaid version to resolve this issues. Especially the one with the reversed property order. That has been resolved in 8.3 I think.

**Comment by ChrisStrykesAgain** [comment]
Changing accounts, as I was signed in to the wrong one previously. Sorry for any potential confusion.

I assumed that GitLab needs to update their mermaid version to resolve the {} issue (and a couple others), but the original post still reproduces using the latest mermaid live editor, as linked.

**Comment by ChrisStrykesAgain** [comment]
Sorry for the double post, but as of this morning, the `#35;` workaround doesn't seem to work, unless I'm inept. [Mermaid Live Editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jbGFzcyBBY3RvclxuICAgICBBY3RvciA6ICMzNTtBY3RvckNvcmUoKSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19/error/UGFyc2UgZXJyb3Igb24gbGluZSAzOgouLi4gQWN0b3IgICAgIEFjdG9yIDogIzM1O0FjdG9yQ29yZSgpCi0tLS0tLS0tLS0tLS0tLS0tLS0tLS1eCkV4cGVjdGluZyAnTkVXTElORScsICdFT0YnLCBnb3QgJ1BVTkNUVUFUSU9OJw)

**Comment by jgreywolf** [comment]
I dont think you are inept.  I would be surprised if this works, since it still starts with "#" which is defined as PUNCTUATION in the code :)

I am going to continue looking into this, in my attempts to get a better understanding of the mermaid code.  Maybe I can even contribute ;)

**Comment by chris579** [comment]
@jgreywolf great, can't wait for your contribution! Until then, I assigned that issue to you so nobody grabs it. Make sure to have a look into our [contributing guidelines](https://github.com/mermaid-js/mermaid/blob/master/CONTRIBUTING.md) and join our Slack if you need assistance. You can find the invite link at the bottom.
