### ISSUE TITLE
Massive whitespace above and below graph

### ISSUE THREAD

**Issue by sadata7** [mermaid-js/mermaid#1984]
**Describe the bug**
Very large charts result in massive amounts of excess whitespace above and below the diagram making it practically unusable.  I was using mermaid to chart a family tree with approximately 400 relationships/nodes. Performance is very acceptable for such an application, so it's unfortunate that I've encountered this issue.

**To Reproduce**
The family tree contains confidential information so I cannot post it, but the problem can easily be reproduced by repeating the simple relationship below.  I'm showing 5 repetitions below. The problem starts manifesting itself after about 50 repetitions and becomes extremely problematic at around 150, getting progressively worse as more elements are added to the graph.

```
flowchart BT
A-->B-->C-->D-->E
A-->B-->C-->D-->E
A-->B-->C-->D-->E
A-->B-->C-->D-->E
A-->B-->C-->D-->E
```

50 repetitions:
![Selection_055](https://user-images.githubusercontent.com/80186985/114657636-7d9b9680-9cbe-11eb-8afc-e22d73ad188a.png)

150 repetitions:
![Selection_056](https://user-images.githubusercontent.com/80186985/114657659-8ab88580-9cbe-11eb-8a15-b43d2e3e310f.png)

Here's what I'm experiencing with the actual family tree. The first example is using the VS Code mermaid extension. Please note the size of the scrollbar handle on the right to get an idea how much empty space is above and below the diagram in addition to the empty space in the visible portion.

![Selection_053](https://user-images.githubusercontent.com/80186985/114657834-d23f1180-9cbe-11eb-8075-ad114cde46f2.png)

The second example is using mermaid in Joplin. Here's what PDF output looks like, and the same amount of empty space is present in the live view.

![Selection_054](https://user-images.githubusercontent.com/80186985/114657823-ce12f400-9cbe-11eb-94e5-09c3c8fd75d8.png)

The problem can also be reproduced in the Live Mermaid Editor. Here's what happens with 500 repetitions of the aforementioned example:

![Selection_057](https://user-images.githubusercontent.com/80186985/114658982-bfc5d780-9cc0-11eb-9759-4777eb21341b.png)

**Expected behavior**
The size should be limited to the visible extent of the graph.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - any OS

**Smartphone (please complete the following information):**
 - any device

**Additional context**

**Comment by blacksun1** [comment]
Adding to this, I am getting the same issue with very long sequence diagrams when previewing in Visual Studio Code and in the live editor. I was using Markdown PDF by yzane.markdown-pdf version 1.4.4 and VS Code 1.55.2 on Windows.

Curiously, I don't get the same issue when I generate a PNG or SVG image using the same diagram with the npm package `@mermaid-js/mermaid-cli`. I'm using version 8.9.2 of mermaid-cli on Windows with nodejs version v14.16.0

**Comment by blacksun1** [comment]
This is how the cli renders the flow chart as discussed above with 200 repetitions

![FlowChart](https://user-images.githubusercontent.com/1436675/115478576-a0f9af00-a285-11eb-8c0b-3651cabb2d91.png)

As you can see, it does now have spacing to the right which I don't think is an issue.

This, however, is how it looks when embedded into a markdown document and previewed using VSCode

![image](https://user-images.githubusercontent.com/1436675/115478777-02218280-a286-11eb-9222-70f486bd3e42.png)

Notice the spacing on the top and bottom.

**Comment by imeikas** [comment]
For SVGs I could fix the whitespace by changing

`<svg ... height="2583" style="max-width: 2670px;" viewBox="-50 -10 2670 2583">`

to

`<svg ... style="max-width: 2670px;max-height:2583px;" viewBox="-50 -10 2670 2583">`

Hope this helps track down the issue

**Comment by naletups** [comment]
For me, the same issue arises for a sequence diagram, for which there are 100 lines (including a 8x `participant` block and some 15 `opt` and `alt` blocks). But it starts already for as few as 25 lines without any `opt` or `alt` blocks. The effect is the worse, the wider the figure is.


If you put the following into the live editor, you'll see already quite some spacing at top and bottom. If you add/remove participants you'll see the effect. Unfortunately, it also depends on the screen resolution/window viewport width.
```mermaid
sequenceDiagram
 autonumber
 participant A
 participant B
 participant C
 participant D
 participant E
 participant F
 participant G
A->>B: Task
A->>B: Task
A->>B: Task
A->>B: Task
A->>B: Task
A->>B: Task
A->>B: Task
A->>B: Task
A->>B: Task
A->>B: Task
A->>B: Task
A->>B: Task
A->>B: Task
A->>B: Task
A->>B: Task
A->>B: Task
```

**Comment by kurtlawrence** [comment]
I am getting similar behaviour with flowcharts

**Comment by jlfwilliams** [comment]
Having this same issue, would love a fix!

**Comment by thegiantbeast** [comment]
If it helps on anything, this regression was introduced with 8.8.1 release -> https://github.com/mermaid-js/mermaid/commit/4dc805d25add19ae07ac9fe8951b4036332e0530

**Comment by thegiantbeast** [comment]
If I switch to `8.8.0` it works as expected. Still haven't found the root cause.

**Comment by tessus** [comment]
We have the same problem in Joplin. People have found a workaround by adding the following css: 

```
.mermaid svg { height: auto; }
```

@knsv ^^^

**Comment by Becheler** [comment]
I am bumping into the same issue with Github rendering. Any news on this front?

**Comment by OmgImAlexis** [comment]
Also hitting this issue on github. Here's an anonymised version of what I'm using.

```
sequenceDiagram
  a->>b: text here
  a->>b: text here
  b->>a: text here  
  a->>b: text here
  a->>c: text here
  c->>d: text here
  c->>e: text here 
  f->>b: text here
  b->>a: text here
  a->>g: text here
  b->>h: text here
```

```mermaid
sequenceDiagram
  a->>b: text here
  a->>b: text here
  b->>a: text here  
  a->>b: text here
  a->>c: text here
  c->>d: text here
  c->>e: text here 
  f->>b: text here
  b->>a: text here
  a->>g: text here
  b->>h: text here
```

**Comment by dkkb** [comment]
> Also hitting this issue on github. Here's an anonymised version of what I'm using.
> 
> ```
> sequenceDiagram
>   a->>b: text here
>   a->>b: text here
>   b->>a: text here  
>   a->>b: text here
>   a->>c: text here
>   c->>d: text here
>   c->>e: text here 
>   f->>b: text here
>   b->>a: text here
>   a->>g: text here
>   b->>h: text here
> ```

+1

**Comment by listx** [comment]
For context, there was a fix for this in #2312 but it was reverted in 38ef0611753fcc1e8ef7de024300614cd4768b8a.

**Comment by athenor** [comment]
I just ran into this exact same issue in two places. I wrote a fairly long sequence diagram in VS Code, then uploaded it to GitLab as a snippet.  

VS Code: 1.68.0, running on Windows 10
Extensions:
- Markdown Preview Enhanced 
- Markdown Preview mermaid Support v1.14.2
- Mermaid Markdown Syntax highlighting v1.3.0

Gitlab 15.0 (viewing in Firefox)

**Comment by berzi** [comment]
The proposed workarounds using `<style>` don't work in places like Gitlab wiki. Please fix.

**Comment by LouisBzh** [comment]
Hi,
I ran in the same issue lately with big flowcharts in a markdown.
When exported to svg the white spaces are not present anymore.
I used the mermaid-cli command:
`mmdc -i ReadMeWithMermaidCodes.md -o ReadMeWithSVG.md`
to generate the new markdown.
Unfortunately I need to run this command each time I update my original file.
I would be nice to have a fix on this problem.

**Comment by Becheler** [comment]
This issue on my Github pages was solved and the massive blank is gone: that's amazing, thanks devs! <3

**Comment by berzi** [comment]
> This issue on my Github pages was solved and the massive blank is gone: that's amazing, thanks devs! ❤️ :

Do you mind explaining how?

**Comment by Becheler** [comment]
> > This issue on my Github pages was solved and the massive blank is gone: that's amazing, thanks devs! heart :
> 
> Do you mind explaining how?

If only I knew! I went back to it today after months of absence, and the blank was gone. You can find the flowchart [here](https://github.com/Quetzal-framework/quetzal_on_OSG/blob/main/README.md) and the code is avaiable on the raw view of the README :) I wish I could be more useful, but mermaid is a (beautiful) mystery to me!

**Comment by nickfyson** [comment]
👋 Excess padding is now being handled on the GitHub side, so that'll be why the problem is fixed in Pages! 🙂 (I believe the underlying Mermaid issue remains.)

**Comment by berzi** [comment]
My issue is on Gitlab so it's not fixed for me. :(

**Comment by aadamsx** [comment]
Same.  See this issue with the Sequence Diagrams in Preview with VS Code.  When exporting to various formats it remains.  Are there any MM devs looking at this, it's been going on for a long time.

**Comment by tekstrand** [comment]
👀 running into this one as well. Would be nice to see the underlying issue here addressed

**Comment by trevorhardy** [comment]
Similar issue with Sphinx on ReadTheDocs

**Comment by NakitaOza** [comment]
> This is how the cli renders the flow chart as discussed above with 200 repetitions
> 
> ![FlowChart](https://user-images.githubusercontent.com/1436675/115478576-a0f9af00-a285-11eb-8c0b-3651cabb2d91.png)
> 
> As you can see, it does now have spacing to the right which I don't think is an issue.
> 
> This, however, is how it looks when embedded into a markdown document and previewed using VSCode
> 
> ![image](https://user-images.githubusercontent.com/1436675/115478777-02218280-a286-11eb-9222-70f486bd3e42.png)
> 
> Notice the spacing on the top and bottom.

Where you able to fix this? I am also facing this problem for mermaid sequence diagrams in md files.

**Comment by berzi** [comment]
That doesn't work where you have no control over CSS, like on Gitlab Wikis.

**Comment by amaze-escape** [comment]
> That doesn't work where you have no control over CSS, like on Gitlab Wikis.

I also arrived here because of this issue in gitlab wiki.

**Comment by eric-cooper** [comment]
I am experiencing similar issues with excessive top/bottom margin (whitespace) for larger flow charts.

This flowchart renders nicely here but in Docsy and in Mac version of VS Code  (v1.17.2) with Markdown Preview Mermaid Support (v1.15.2) there are excessive top and bottom margins - each roughly same height as flowchart (below).

Note: setting useMaxWidth to false does make a difference but doesn't solve problem completely. ;-)

%%{init: {"flowchart": {"useMaxWidth": false}}}%%


```mermaid
flowchart LR
    classDef subgraph_padding fill:none,stroke:none

    COMP(Composite Application)

    subgraph STD["Procedure Camera AI Workload (25 fps)"]

      subgraph ugly_hack1 [ ]

        C1(Endoscope Camera)
        S1(Ingest Video);
        P1(Prepare Image);

        subgraph I1[Image Inference Block]
           MR1[( Model Repo)]
           TTD(Tooltip Detection)
           ASD(Anat. Struct. Detection)
        end

        E1(Export Results);
      end
    end

    subgraph SPD["PTZ Camera AI Workload (1 fps)"];

      subgraph ugly_hack2 [ ]

         C2(PTZ Camera);
         S2(Ingest Video);
         P2(Prepare Image);

        subgraph I2[Image Inference Block]
            MR2[( Model Repo)]
            PHD(Phase Detection)
            FB(Face Blur)
            OD(Object Detection)
         end

         E2(Export Results);
       end
    end

    subgraph VID[Video Controller]
      VC(Video Composite)
      VS(Video Switch)
    end
 
 subgraph SC[Shared Components]
      SMR[(Global Model Repo)]
    end

 %% create transparent subgraphs to kludge desired layout for subgraph titles. -ec 22.09.19
    class ugly_hack1 subgraph_padding
    class ugly_hack2 subgraph_padding

    COMP--contains-->STD;
    COMP--contains-->SPD;
    COMP--contains-->SC;
    COMP--contains-->VID;

%% Procedure Camera AI Workflow, etc.
    C1-->S1;
    S1-->P1;
    P1-->TTD;
    P1-->ASD;
    TTD-->E1;   
    ASD-->E1; 

%% PTZ Camera AI Workflow, etc.
    C2-->S2;
    S2-->P2;
    P2-->PHD;
    P2-->FB;
    P2-->OD;
    PHD-->E2;   
    FB-->E2;   
    OD-->E2;   

%% Video Controller and Display
    C1-->VC
    C2-->VC
    E1-->VC
    E2-->VC
    VC-->VS
    VS-->QD[Quad Display]
    VS-->SD[Single Display]
    VS-->TP[Telepresense]
    VS-->DICOM[(DICOM Database)]
    
%% Inference Workloads and Model Repos
    TTD-.uses.->MR1;
    ASD-.uses.->MR1;
    PHD-.uses.->MR2;
    FB-.uses.->MR2;
    OD-.uses.->MR2;
    MR1-.uses.->SMR;
    MR2-.uses.->SMR;

```

**Comment by EvertonSA** [comment]
+1

**Comment by amith-kumarg** [comment]
If you are facing this issue with MermaidJS macro in Atlassian Confluence, [here](https://medium.com/@amithkumarg/resolved-mermaid-js-before-and-after-diagram-massive-whitespaces-big-gap-issue-in-confluence-690e5c79edc1) is how to resolve it until this issue is addressed.

**Comment by amithkumarg** [comment]
If you are facing this issue with MermaidJS macro in Atlassian Confluence, [here](https://medium.com/@amithkumarg/resolved-mermaid-js-before-and-after-diagram-massive-whitespaces-big-gap-issue-in-confluence-690e5c79edc1) is how to resolve it until this issue is addressed.

**Comment by ShivamBang98** [comment]
I sort of used a workaround for this in my Confluence page. Here's what I did:
1. Create the diagram using mermaid.live
2. Copy the markdown and import it into draw.io (Confluence's embedded draw.io) as mentioned here - https://drawio-app.com/blog/create-mermaid-diagrams-in-draw-io/
3. Paste the markdown separately in the same doc with the diagram.

This also solved another problem for me, which was that for larger diagrams, I was unable to expand them and see the smaller text. I was also able to wrap it up neatly inside an "expand" macro, so it ended up looking pretty neat. Attached screenshot for reference.

![Screenshot 2023-08-29 at 11 19 19 PM](https://github.com/mermaid-js/mermaid/assets/140058716/bb740433-0473-4ef4-8dae-f9abacbe1239)

**Comment by o6uoq** [comment]
Any update? This ticket is 3+ years old, simply to remove whitespace. This is enough to make some users deter to other tools over Mermaid.

**Comment by steveswinsburg** [comment]
Still unresolved. Workaround  for me to remove whitespace is using imagemagick:

`magick input.png -trim +repage output-trimmed.png`

Examples:

**Input:**
<img width="50%" alt="Image" src="https://github.com/user-attachments/assets/1d4c4209-43b5-4e04-abee-79a19f0b4479" />

**Output:**
<img width="50%" alt="Image" src="https://github.com/user-attachments/assets/88ec529b-95cb-41b3-bfc6-35e83a92dd8f" style="border: 2px solid grey;" />
