### ISSUE TITLE
Sandbox mode results in invalid document on parse errors

### ISSUE THREAD

**Issue by dometto** [mermaid-js/mermaid#3153]
When using `securityLevel: 'sandbox'`, a parse error in a diagram results in a *second* iframe with exactly the same ID as the first (correctly placed) iframe, thus rendering the main document invalid. In addition, the "parse error" image is not shown.

This is reproducible on codepen: https://codepen.io/dometto/pen/XWZQBbb

**To Reproduce**
1. Initialize mermaid with `securityLevel: 'sandbox'`.
2. Add a diagram with invalid syntax to the page

**Expected behavior**
The iframe should render the standard mermaid "A parse error occurred" svg, no second iframe should be present.

**Screenshots**

See https://codepen.io/dometto/pen/XWZQBbb

**Code Sample**

See https://codepen.io/dometto/pen/XWZQBbb

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: Firefox, Chrome

**Comment by dometto** [comment]
Still present on mermaid `9.1.3`. Can someone confirm this is a bug, or am I misconfiguring?

**Comment by knsv** [comment]
This looks like a bug. We will plan a fix

**Comment by dometto** [comment]
Thanks @knsv! Is there an approximate timeline on this by any chance? No problem if not of course.

**Comment by knsv** [comment]
I am struggling to reproduce this outside of code pen. Tried, a simple securityLevel iframs, rendered fine. 

"I wonder if it could be related to this being run in Codepen which is in an iframe. Perhaps that causes havoc with the selectors?"

Also rendered fine.

**Comment by knsv** [comment]
If you removed the red code, it works:


![Image](https://user-images.githubusercontent.com/5837277/194898845-aa5bff4a-b1a7-40eb-879f-f85d3f252d8e.png)

But I suspect the links will fail due to the increased security restrictions in the iframe:


![Image](https://user-images.githubusercontent.com/5837277/194899226-c38fa5e5-94df-4c00-afe5-3cf16dafaddb.png)

**Comment by dometto** [comment]
> If you removed the red code, it works

Just to make sure, I know it works when the diagram is valid. The point of this issue that there is a bug for *in*valid diagrams: you would expect a sane error message (as one gets when mermaid is run without `securityLevel: 'sandbox'`), but instead the document is broken. I set up the codepen as a reproducible example, but I originally came across this bug when working on Mermaid integration in [gollum](https://github.com/gollum/gollum), in which the diagrams are not themselves included in an iframe.

**Comment by MasonM** [comment]
I looked into this and I'm pretty sure it was fixed in https://github.com/mermaid-js/mermaid/commit/9a0d5e31b77fcea6b20338078e46c78d5a8a7c3c, which hasn't been released yet

**Comment by dometto** [comment]
@MasonM there's an improvement on `v9.2` since there is no longer the second iframe (with the same id as the first), and so the page as a whole doesn't break. However, the standard mermaid "Aparse error occurred" svg is not displayed (screenshot below). Is that expected behavior?

<img width="836" alt="Screenshot 2022-11-28 at 21 48 51" src="https://user-images.githubusercontent.com/147111/204377912-cc1ab67d-318b-4e91-bd82-4151b92cee57.png">

**Comment by MasonM** [comment]
@dometto Yeah,seems there's a second bug here. When I step through the code, there's an "svgEl.viewBox.baseVal is null" error triggered by the following line:
https://github.com/mermaid-js/mermaid/blob/9a0d5e31b77fcea6b20338078e46c78d5a8a7c3c/src/mermaidAPI.ts#L326

**Comment by bartkamphorst** [comment]
This issue is still present in mermaid `v.9.3.0`. @MasonM Thanks for working on this. Any further insights into why mermaid isn't properly rendering the error svg in the iframe in sandbox mode?

**Comment by jgreywolf** [comment]
Opened new issue (#4036) for additional bug
